export const TRANSACTION_DATA = [
  {
    id: 1,
    title: 'Monthly Income',
    createdAt: '10:30 am',
    category: 'Salary',
    paymentMethod: 'Online',
    balance: 80000,
    amount: 80000,
    type: 'income',
  },
  {
    id: 2,
    title: 'Utility',
    createdAt: '10:30 am',
    category: 'Bills',
    paymentMethod: 'Cash',
    balance: 6000,
    amount: 9999,
    type: 'expense',
  },
  {
    id: 3,
    title: 'Grocery Items',
    createdAt: '10:30 am',
    category: 'Grocery',
    paymentMethod: 'Cash',
    balance: 20000,
    amount: 999,
    type: 'expense',
  },
  {
    id: 4,
    title: 'Car Instalment',
    createdAt: '10:30 am',
    category: 'Rent',
    paymentMethod: 'Cash',
    balance: 15000,
    amount: 999,
    type: 'expense',
  },
  {
    id: 5,
    title: 'School Fee',
    createdAt: '10:30 am',
    category: 'Utility',
    paymentMethod: 'Cash',
    balance: 1000,
    amount: 999,
    type: 'expense',
  },
  {
    id: 6,
    title: 'Doctor Fee',
    createdAt: '10:30 am',
    category: 'Health',
    paymentMethod: 'Cash',
    balance: 1000,
    amount: 999,
    type: 'expense',
  },
  {
    id: 7,
    title: 'Medicines',
    createdAt: '10:30 am',
    category: 'Health',
    paymentMethod: 'Cash',
    balance: 1000,
    amount: 999,
    type: 'expense',
  },
];

export const TRANSACTION_TYPE_EXPENSE = 'expense';
