export const TRANSACTION_DATA = [
  {
    id: 1,
    title: 'Monthly Income',
    createdAt: '10:30 am',
    category: 'Salary',
    paymentMethod: 'Online',
    balance: '80000',
    amount: '80000',
    type: 'income',
    attachment: [1, 2, 3, 4],
  },
  {
    id: 2,
    title: 'Utility',
    createdAt: '10:30 am',
    category: 'Bills',
    paymentMethod: 'Cash',
    balance: '6000',
    amount: '9999',
    type: 'expense',
    attachment: [1],
  },
  {
    id: 3,
    title: 'Grocery Items',
    createdAt: '10:30 am',
    category: 'Grocery',
    paymentMethod: 'Cash',
    balance: '20000',
    amount: '999',
    type: 'expense',
    attachment: [1, 2, 3],
  },
  {
    id: 4,
    title: 'Car Instalment',
    createdAt: '10:30 am',
    category: 'Rent',
    paymentMethod: 'Cash',
    balance: '15000',
    amount: '999',
    type: 'income',
    attachment: [1, 2, 3, 4],
  },
  {
    id: 5,
    title: 'School Fee',
    createdAt: '10:30 am',
    category: 'Utility',
    paymentMethod: 'Cash',
    balance: '1000',
    amount: '999',
    type: 'expense',
    attachment: [1],
  },
  {
    id: 6,
    title: 'Doctor Fee',
    createdAt: '10:30 am',
    category: 'Health',
    paymentMethod: 'Cash',
    balance: '1000',
    amount: '999',
    type: 'expense',
    attachment: [1, 2, 3, 4],
  },
  {
    id: 7,
    title: 'Medicines',
    createdAt: '10:30 am',
    category: 'Health',
    paymentMethod: 'Cash',
    balance: '1000',
    amount: '999',
    type: 'income',
    attachment: [1, 2, 3, 4],
  },
];

export const CATEGORY = ['Labour Changes', 'Profit', 'Sale', 'Salary'];

export const PAYMENT = ['Cash', 'Online', 'Bank Transfer', 'Cheque'];

export const LEDGER_DATA = [
  {
    id: 1,
    title: 'Title 1',
    createdAt: '15-07-2022',
    netBalance: '80000',
  },
  {
    id: 2,
    title: 'Title 2',
    createdAt: '15-07-2022',
    netBalance: '80000',
  },
  {
    id: 3,
    title: 'Title 3',
    createdAt: '15-07-2022',
    netBalance: '80000',
  },
  {
    id: 4,
    title: 'Title 4',
    createdAt: '15-07-2022',
    netBalance: '80000',
  },
  {
    id: 5,
    title: 'Title 5',
    createdAt: '15-07-2022',
    netBalance: '80000',
  },
  {
    id: 6,
    title: 'Title 6',
    createdAt: '15-07-2022',
    netBalance: '80000',
  },
  {
    id: 7,
    title: 'Title 7',
    createdAt: '15-07-2022',
    netBalance: '80000',
  },
  {
    id: 8,
    title: 'Title 8',
    createdAt: '15-07-2022',
    netBalance: '80000',
  },
];
