const appColors = {
  white: '#FFFFFF',
  black: '#000000',
  primary: '#03045E',
  gradient2: '#60efff',
  red: '#C11F1F',
  expenseStatus: '#AF1D1D',
  expenseIconBackground: '#FCF5F7',
  expenseBackground: '#FCF5F7',
  green: '#1CB023',
  incomeStatus: '#199F1F',
  incomeIconBackground: '#EDFCEE',
  incomeBackground: '#F8FFF9',
  text: '#011C3D',
  subText: '#002E66',
  background: '#EBF3FF',
  inputBackground: '#ebf4f5',
  inputIconColor: '#999999',
  cardBackground: '#EBF3FF',
  categoryBackground: '#EBDDF8',
  categoryText: '#7326BA',
  paymentMethodBackground: '#D7FEFD',
  paymentMethodText: '#3EA39F',
  backgroundWithOpacity: 'rgba(91,90,98,0.3)',
  transparent: 'transparent',
};

export default appColors;
